import type { Metadata } from "next";
import { FC, ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import AuthProvider from "@/providers/AuthProvider";
import Link from "next/link";
import Image from "next/image";
import "@styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="font-sans grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20">
          <main className="flex flex-col gap-[32px] row-start-2 items-center sm:items-start">
            <Image
              className="dark:invert"
              src="/next.svg"
              alt="Next.js logo"
              width={180}
              height={38}
              priority
            />
            <AuthProvider>{children}</AuthProvider>
          </main>

          <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center">
            {[
              { href: "/", icon: "/file.svg", text: "Home" },
              { href: "/about", icon: "/window.svg", text: "About" },
              { href: "/dashboard", icon: "/globe.svg", text: "Dashboard" },
            ].map(({ href, icon, text }) => (
              <Link
                key={text}
                href={href}
                rel="noopener noreferrer"
                className="flex items-center gap-2 hover:underline hover:underline-offset-4"
              >
                <Image
                  src={icon}
                  alt={`${text} icon`}
                  width={16}
                  height={16}
                  aria-hidden
                />
                {text}
              </Link>
            ))}
          </footer>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
