server:
  host:
    mariadb: 127.0.0.1
  port: 9080

spring:
  application:
    name: youtube
  datasource:
    username: root
    password: root
    url: jdbc:mysql://${server.host.mariadb}:3309/live2ver
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        dialect.storage_engine: innodb
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        #implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        data:
          mongodb:
            repository:
              query: DEBUG
        security: DEBUG
        web:
          filter: DEBUG

security:
  jwt:
    secret: live2ver-web-jwttoken-startapp!@  # 최소 32개의 문자열 (256bit)